name: banck_accounts_cards
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.1
  excel: ^4.0.6
  filepicker_windows: ^2.1.4
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  image_path: "static/icon.png"
  android: true
  ios: true
  windows:
    generate: true
    image_path: "static/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - static/
